### ISSUE TITLE
404 Datasheet Amicon 7106

### ISSUE THREAD

**Issue by 8bignic8** [CursedHardware/hanshow#1]
missing Datasheet in HS_EL5102-0_V2-4 

https://datasheet.lcsc.com/szlcsc/2001071135_AMICCOM-Elec-A71X06AQFI-Q_C479510.pdf

**Comment by mo10** [comment]
Thanks.

**Comment by cheng3100** [comment]
Hi, I found this link still 404 now.  Is there anyone gives a valid download link ? Maybe it is better to put the file directly inside the project

**Comment by mo10** [comment]
[A7106 Datasheet.pdf](https://github.com/user-attachments/files/17011804/A7106.Datasheet.pdf)

**Comment by cheng3100** [comment]
thanks! By the way, I have to say that I really don't understand why some chip verndor always hide their spec and only offer with some words like "please contact with saler" .

For example I find a esl tag with `qorvo gp570` chip inside. But I still can't find any details spec&sdk after search for a long time...
