### ISSUE TITLE
新增新板型

### ISSUE THREAD

**Issue by alanfans** [CursedHardware/hanshow#3]
型号：Stellar-L3@ E31A 2.9
板号：HS_EL5102_9M_61_01
cpu：TLSR8359F512ET32 ，这个U不带bluetooth
color: B/W/R

![image](https://user-images.githubusercontent.com/8871739/232959880-f4e070c8-c646-4fce-8f6d-2134cbb94265.png)
![image](https://user-images.githubusercontent.com/8871739/232959998-189a2096-8475-474f-824a-80f167123d79.png)

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/232960390-1166a90d-ad19-487b-b301-55caa1294494.png)

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/232960470-3b31208c-a9fa-4fff-9ac2-97eb80bfab79.png)

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/232960536-cfc3db28-947e-4bcd-972c-a17104748184.png)

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/232960609-d17bb685-a45d-4458-86d7-a14b7de2f12c.png)

**Comment by alanfans** [comment]
芯片TLSR8359 官网说明，文档，各种信息都没有说有bluetooth,外国大佬逆向发现这soc带低功耗蓝牙BLE,这是什么操作
https://www.youtube.com/watch?v=geqv2qlGmOc 大佬地址
但是我刷了固件，蓝牙又没出来，神奇。

**Comment by andelf** [comment]
同MCU, PCB 布局不同的我有. 

> 这个U不带bluetooth

带, 这么大 flash, 只要 rf 支持, 协议栈必然放得下

官方文档里就有 BLE 说明.

```
TLSR825x is built around a 32-bit MCU running up to 48MHz. It has 14bit ADC with PGA, AMIC, DMIC, stereo audio output, 6-channel PWM, one quadrature decoder (QDEC), and flexible GPIO interfaces.
-96dBm@Bluetooth® LE 1Mbps, -99.5dBm@802.15.4 250kbps, maximum Tx output power is +10dBm. It is embedded with LDO and DCDC, the power supply is 1.8 ~ 3.6V, and provides low power consumption: 5.3mA@Rx fullchip, 4.8mA@Tx 0dBm fullchip, <1uA@Sleep+SRAM>, 0.4uA@Sleep.
```

**Comment by andelf** [comment]
能否整成 PR 格式发下相关信息.
